# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Riley Jones Design
email: jonesr423@gmail.com
description: >
  Riley Jones Design | St. Louis. Impactful web design and logo design that amplifies brands
  to further connect with their audiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rileyjonesdesign.com" # the base hostname & protocol for your site
behance_username: RiJones
twitter_username: rileyj_s
github_username:  rileyj-s
instagram_username: rileyj_s
medium_username: '@rileyj_s'

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
