# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Riley Jones Design
email: jonesr423@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Riley Jones Design. Impactful web design and identities for brands who want their
  voices to be loud and heard from all directions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
behance_username: RiJones
twitter_username: rileyj_s
github_username:  rileyj-s
instagram_username: rileyj_s
medium_username: '@rileyj_s'

# Build settings
markdown: kramdown
